version: '3.4'

services:

  flight:
    image: flight
    container_name: flight_app
    build:
      context: .
      target: development
    volumes:
      - .:/flight
      - postgres_vol:/vol/postgres
    restart: always
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    container_name: flight_db
    environment:
      - DB_HOST=${DB__HOST}
      - POSTGRES_DB=${DB__NAME}
      - POSTGRES_USER=${DB__USERNAME}
      - POSTGRES_PASSWORD=${DB__PASSWORD}
    ports:
      - "${DB__PORT}:5432"
    expose:
      - ${DB__PORT}
    restart: always
    volumes:
      - .:/discord
      - postgres_vol:/var/lib/postgresql/data

  pgadmin_discord:
    container_name: discord_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5051:80"
    depends_on:
      - db

volumes:
  postgres_vol:
